---
config:
  theme: redux-dark
  layout: dagre
---
flowchart TD
    p1[["→ Overview"]]
    subgraph s5["getUsersPresentNextWeekWithThereRoles()"]
        n1["Initialize an array users[]"]
        n2["Initialize an array roles[]"]
        n3["SQL - Get all roles where priority_role isn't 0"]
        n4["Foreach Role"]
        n5["SQL - Get all users_ids with at least 1 PRESENT or PARTIALLY_ABSENT who have this role"]
        n6["Foreach user"]
        n7["Add to this user the arrays:<br>role_priority,<br>technician_1_assignation[0,0,0],<br>technician_2_assignation[0,0,0],<br>technician_3_assignation[0,0,0],<br>available_periods_counter<br>1st number is the min assignation<br>2nd number is the max assignation<br>3th is the number on time assigned"]
        n8["RETURN: An array of users[]"]
  end
    back1[["← Overview"]]

    p1 --> s5
    n1 --> n2
    n2 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 -.-> n4 & n6
    n7 --> n8
    n8 --> back1

%% Lien de retour vers le fichier parent
click back1 "01_overview.mmd" "Retour à la vue d'ensemble"

