---
config:
  theme: redux-dark
  layout: dagre
---
flowchart TD
    p1[["→ Overview"]]
    subgraph s7["canPlanningBeCopiedFromCurrentWeek"]
        n1["SQL - Get current week presences"]
        n2["TODO: check if possible to copy the current week to the next week"]
        n3["RETURN: boolean"]
  end
    back1[["← Overview"]]

    p1 --> s7
    n1 --> n2
    n2 --> n3
    n3 --> back1

%% Lien de retour vers le fichier parent
click back1 "01_overview.mmd" "Retour à la vue d'ensemble"

