---
config:
  theme: redux-dark
  layout: dagre
---
flowchart TD
    p1[["→ Overview"]]
    subgraph s2["generateNextWeekPlanningAttribution()"]
        n1{"Current week period count === next week period count ?"}
        %% A voir avec Jocelin si on peut faire une comparaison de matrice au lieu d'une somme de presences
        %% Si trop compliqué controller si le tableau de présence d'un user a été mis à jour les 7 derniers jours
        n2[["generateNextWeekPlanning()"]]
        n3["Sort users_ids[] with the least assignation possible, then the role priority on start of the array"]
        n4["Sort presences[] with the least all_available_technician on the start of the array"]
        n5["Foreach presence"]
        n6["SWITCH(all_available_technicians) count"]
        n7["CASE 0: CONTINUE"]
        n8["CASE 1 to 3:"]
        n9["CASE 4 or more:"]
        n10{"Do we have an other presence in our array presences[]?"}
        p2[["attribution_cas_1_a_3_techniciens()"]]
        p3[["attribution_cas_4_plus_techniciens()"]]
        n11["RETURN: periods[]"]
  end
    back1[["← Overview"]]

    p1 --> s2
    n1 --YES--> n2
    n2 --> n11
    n1 --NO--> n3
    %%n2 --> n4
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7 & n8 & n9
    n7 & p2 & p3 --> n10
    n10 --YES--> n5
    n10 --NO--> n11
    n8 --> p2
    n9 --> p3
    n11 --> back1

%% Liens cliquables
click back1 "01_overview.mmd" "Retour à la vue d'ensemble"
click p1 "07_attribution_cas_1_a_3_techniciens.mmd" "Ouvrir le détail pour 1 à 3 techniciens"
click p2 "08_attribution_cas_4_plus_techniciens.mmd" "Ouvrir le détail pour 4+ techniciens"

%% Coloration des nodes à corriger
style n2 fill:#ff0000,stroke:#000000,stroke-width:2px
