---
config:
  theme: redux-dark
  layout: dagre
---
%% Sous-processus détaillé du fichier 06_generateNextWeekPlanning_attribution.mmd
%% Appelé lorsque CASE 1 to 3 techniciens disponibles
flowchart TD
    p1[["→ generateNextWeekPlanningAttribution()"]]
    subgraph s1["assignCaseOneToThreeTechnicians()"]
        n1["Foreach available_first_technician"]
        n2{"Do user_id max_assignation as first_technician is reach?"}
        n5["Assign this user_id to this period as first_technician"]
        n6["Increment this user_id assigned_first_technician with +1"]
        n7{"Do available_second_technician is more or egal to 2?"}
        n10{"Do user_id is egal to first_technician in this period?"}
        n13["Foreach available_second_technician"]
        n14{"Do user_id max_assign_second_technician is reach?"}
        n17["Assign this user_id to this period as second_technician"]
        n18["Increment this user_id assigned_second_technician with +1"]
        n19{"Do available_third_technician is more or egal to 3?"}
        n22["Foreach available_third_technician"]
        n23{"Do user_id is egal to first_technician of second_technician in this period?"}
        n26{"Do user_id max_assign_third_technician is reach?"}
        n29["Assign this user_id to this period as third_technician"]
        n30["Increment this user_id assigned_third_technician with +1"]
  end
    back1[["← generateNextWeekPlanningAttribution()"]]

    p1 --> s1
    n1 --> n2
    n2 --NO-->  n5
    n2 --YES--> n1
    n5 --> n6
    n6 --> n7
    n7 --NO--> n1
    n7 --YES--> n13
    n10 --YES--> n13
    n10 --NO--> n14
    n13 --> n10
    n14 --NO--> n17
    n14 --YES--> n13
    n17 --> n18
    n18 --> n19
    n19 --NO--> n1
    n19 --YES--> n22
    n22 --> n23
    n23 --YES--> n22
    n23 --NO--> n26
    n26 --YES--> n22
    n26 --NO--> n29
    n29 --> n30
    n30 --> back1

%% Lien de retour vers le fichier parent
click back1 "06_generateNextWeekPlanningAttribution.mmd" "Retour à la logique d'attribution principale"

