---
config:
  theme: redux-dark
  layout: dagre
---
%% Sous-processus détaillé du fichier 06_generateNextWeekPlanning_attribution.mmd
%% Appelé lorsque CASE 4 or more techniciens disponibles
flowchart TD
    p1[["→ generateNextWeekPlanningAttribution()"]]
    subgraph s1["assignCaseFourOrMoreTechnicians()"]
        n1["Foreach technician_X_assignation (where X = 1 to 3)"]
        n2["Get the list_of_possible_assignated_users[user_id]"]
        n3["Foreach user_id"]
        n4{"Do user_id max_assignation as X_technician is reach? (where X = first, second or third)"}
        n5["Assign this user_id to this period as X_technician"]
        n6["Increment this user_id assigned_X_technician with +1"]
        n7{"Do we have all technician_X_assignation done?"}
  end
    back1[["← generateNextWeekPlanningAttribution()"]]

    p1 --> s1
    n1 --> n2
    n2 --> n3
    n3 --> n4
    n4 --NO--> n5
    n4 --YES--> n3
    n5 --> n6
    n6 --> n7
    n7 --NO--> n1
    n7 --YES--> back1

%% Lien de retour vers le fichier parent
click back1 "06_generateNextWeekPlanningAttribution.mmd" "Retour à la logique d'attribution principale"

